version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    command: ["./server"]

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    command: ["./client", "-email", "user1@ercom.fr"]

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    command: ["./client", "-email", "user2@ercom.fr"]

  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    command: ["./client", "-email", "user3@ercom.fr"]
