services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    depends_on:
      - database
    ports:
      - "50051:50051"
      - "8080:8080"
    command: ["./server"]

  database:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    depends_on:
      - server
    command: ["./client", "-email", "user1@ercom.fr"]

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    depends_on:
      - server
    command: ["./client", "-email", "user2@ercom.fr"]

  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    depends_on:
      - server
    command: ["./client", "-email", "user3@ercom.fr"]
