FROM golang:1.24 AS build
WORKDIR /app
ADD . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine:latest
COPY --from=build /app/server .
COPY --from=build /app/migrations ./migrations
EXPOSE 50051
EXPOSE 8080
CMD ["./server"]
